Feature/get users
indigotech/onboard-gabriel-minossi pull request #19
Opened 2020-09-09 21:10 UTC by gordominossi

2020-09-10 13:41 UTC, alanraso requested changes

2020-09-10 13:41 UTC, alanraso commented on src/graphql-setup.ts
> +}
Outras duas informações importantes que o client pode querer saber são o total de usuários e se tem também usuários anteriores ao estado de paginação que foi escolhido.

2020-09-10 13:41 UTC, alanraso commented on src/test/index.ts
> +        hasMore = response.body.data.users.hasMore === 'true';
Não era pra ele retornar um boolena de verdade em vez da string "true"?

2020-09-10 13:41 UTC, alanraso commented on src/test/index.ts
> +        })).body.data.login.token
Se você fizer a mutation de login para obter um token e a mutationde login estiver com problemas, todos os seus testes de listagem de usuários vão falhar, sendo que eles podem nem ter problemas. Faz sentido?

A ideia desses testes E2E é que você consiga testar as queries/mutations de forma separada e independente, porque assim você consegue localizar melhor onde estão os bugs e a falha em uma delas não necessariamente compromete as outras. Como vc pode fazer nesse caso aqui?

2020-09-10 13:41 UTC, alanraso commented on src/test/index.ts
> +      expect(existingUsersCount).to.equal(allUsers.length)
Novamente você está testando pouca coisa aqui, né? Fazer várias queries, concatenar os usuário e verificar apenas o tamanho da lista não garante muita coisa sobre o funcionamento dessa query. É importante pensar em testes mais completos pra tentar pegar o máximo de bugs possível ainda no processo dedesenvolvimento.

2020-09-10 13:41 UTC, alanraso commented on src/test/index.ts
> +    });
Esse é um exemplo interessante de se testar (a ordenação). Mas ainda faltam algumas coisas (que não necessaraimente precisam estar no mesmo teste), por exemplo:

- O retorno correto dos outros campos de usuário
- A paginação correta para diferentes inputs de count/skip

2020-09-10 13:41 UTC, alanraso commented on src/test/index.ts
> +      }
Não acho uma boa você fazer várias queries para realizar um teste. Talvez você pudesse fazer um `it` pra cada caso específico que você queira testar e verificar o resultado. Na prática, quem usar o seu server vai querer fazer uma request por vez e pegar os resultados corretos. E isso você consegue testar de forma mais organizada com um caso de uso por vez.

2020-09-10 21:07 UTC, gordominossi commented on src/test/index.ts
> +        hasMore = response.body.data.users.hasMore === 'true';
✅

2020-09-11 11:55 UTC, matheusflds commented on .env
> +GRAPHQL_HOST=localhost
agora que tem o sample, esse cara poderia ir pro .gitignore não?

2020-09-11 11:59 UTC, matheusflds commented on src/graphql-props.ts
> +        userRepository.find({ take: count, skip, order: { name: 'ASC' } }),
tem o `findAndCount` também se for do teu interesse :)

2020-09-11 12:44 UTC, alanraso commented on src/entity/User.ts
> +    id: string;
Sabe se isso converteu no seu banco esse campo pra string também? O TypeORM lê os tipos do Typescript pra criar as colunas no banco como tipo "certo" no postgres, mas nesse caso eu não sei se funciona porque é um id incremental (1, 2, 3...)

Se no banco ele ainda for um número, vc teria um misslead aqui, porqueno Javascript seria número, mas o Typescript tá falando que é string.

2020-09-11 12:44 UTC, alanraso commented on src/test/user-seeds.ts
> +    })).body.data.login.token;
Acho que o seed aqui tá desatualizado por conta do posicionamento fas branches né?

2020-09-11 12:44 UTC, alanraso commented on src/test/index.ts
>        expect(response.body.data.login.user).to.contain(expectedResponse);
Talvez fosse mais assertivo você testar com `to.be.deep.eq`, assim você compara se o objeto está exatamente como esprado, e não que apenas contém.

2020-09-11 12:44 UTC, alanraso commented on src/test/index.ts
> +      user.id = user.id.toString();
Ah, isso responde o primeiro comment.

2020-09-11 12:44 UTC, alanraso commented on src/test/index.ts
> +      expect(expectedUsers).to.eql(response.body.data.users.users);
Aqui que aqui também poderia usar o `deep.eq`?

2020-09-11 12:44 UTC, alanraso commented on src/test/index.ts
> +    describe('Pagination', () => {
Talvez mais 2 casos para testar o caso de ele retornar menos usuários que o parâmetro "count" (porque estava quase acabando os usuários) e um outro caso pra ver se ele retorna uma lista vazia mesmo quando o "skip" é mais alto que o número de usuários?

2020-09-11 13:05 UTC, gordominossi commented on .env
> +GRAPHQL_HOST=localhost
Boa, pode sim :)

2020-09-11 13:05 UTC, gordominossi commented on src/entity/User.ts
> +    id: string;
Eu converti no banco na mão :/

2020-09-11 13:06 UTC, gordominossi commented on src/test/user-seeds.ts
> +    })).body.data.login.token;
Sim, acabou virando bagunça eu ter saído da `chore-seed` e dado rebase na `develop`

2020-09-11 13:07 UTC, gordominossi commented on src/test/index.ts
> +    describe('Pagination', () => {
Adicionarei

2020-09-11 13:39 UTC, Mitsuo-Yoshida commented on src/test/user-seeds.ts
> +    })).body.data.login.token;
Então não é bom vc mudar a base do seu PR?
Ou voltar a base da branch para la e garantir q o outro PR #18 esteja mergeado antes?
Q vi q ta saindo da develop
Mas o PR ta com base na branch

2020-09-11 13:42 UTC, Mitsuo-Yoshida commented on src/graphql-props.ts
> +      ]);
Só mostrando como ficaria:
```suggestion
      const [users, usersCount] = await userRepository.findAndCount({ take: count, skip, order: { name: 'ASC' } });
```

2020-09-11 14:07 UTC, gordominossi commented on src/test/user-seeds.ts
> +    })).body.data.login.token;
Fechei o outro PR e dei rebase na develop :)

2020-09-11 14:22 UTC, gordominossi commented on src/entity/User.ts
> +    id: string;
Estou usando uuid agora, que é do mesmo tipo string que o GraphQL retorna. Deve facilitar os testes.

2020-09-11 14:23 UTC, gordominossi commented on src/graphql-props.ts
> +      ]);
✅

2020-09-11 14:27 UTC, gordominossi commented on src/test/user-seeds.ts
> +    })).body.data.login.token;
Dei o merge da outra branch na develop e o rebase de novo

2020-09-11 14:37 UTC, gordominossi commented on src/test/index.ts
>        expect(response.body.data.login.user).to.contain(expectedResponse);
O .to.deep.equal dá no mesmo que o .to.eql

2020-09-11 14:38 UTC, gordominossi commented on src/test/index.ts
> +      expect(expectedUsers).to.eql(response.body.data.users.users);
O `.to.deep.equal` dá no mesmo que o `.to.eql`

2020-09-11 14:38 UTC, gordominossi commented on src/test/index.ts
> +      expect(expectedUsers).to.eql(response.body.data.users.users);
Mudei pra melhorar a legibilidade

2020-09-11 15:59 UTC, alanraso approved these changes

2020-09-11 15:59 UTC, alanraso commented on src/test/index.ts
> +      expect(loginResponse.body, 'Error expected').to.have.property('errors');
Não sei se vc planejou fazer isos num PR separado, o que é bem justo, mas aqui poderia fazer e testar aquele tratamento de erros esperto que conversamos.

2020-09-11 16:30 UTC, Mitsuo-Yoshida approved these changes

2020-09-11 17:10 UTC, gordominossi commented on src/test/index.ts
> +      expect(loginResponse.body, 'Error expected').to.have.property('errors');
Será num PR separado, achei que não entra no escopo da feature aqui
(Se bem que outras coisas aqui tbm não, mas...)

2020-09-11 17:10 UTC, merged